### ISSUE TITLE
Issue with beef-xss

### ISSUE THREAD

**Issue by Techsmobile** [Hax4us/termux-tools#1]
apt install beef-xss
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 beef-xss : Depends: clang (<= 5.0.0) but 6.0.0-1 is to be installed
            Depends: libllvm (<= 5.0.0) but 6.0.0-1 is to be installed

**Comment by Wall3rHM2** [comment]
me too

**Comment by HYDR4-5N1FF3R** [comment]
downgrading the clang and libllvm to 5.0.0 fixed it

pkg install clang=5.0.0 libllvm=5.0.0

**Comment by Hax4us** [comment]
You can reopen if u still have this issue

**Comment by MercifulJake** [comment]
i did this and it says unable to locate 5.0.0

**Comment by Hax4us** [comment]
Give output of `apt update`

**Comment by MercifulJake** [comment]
when i put "pkg install clang=5.0.0 libllvm=5.0.0"
it doesnt find the location

**Comment by Hax4us** [comment]
Give output / screenshot after `apt update`

**Comment by MercifulJake** [comment]
Reading package lists... Done
Building dependency tree
Reading state information... Done
ALL packages are up to date
Reading pakage lists... Done
Building dependency tree
Reading state information... Done
E: Version '5.0.0' for 'clang' was not found

**Comment by MercifulJake** [comment]
Reading package lists... Done
Building dependency tree
Reading state information... Done
ALL packages are up to date
Reading pakage lists... Done
Building dependency tree
Reading state information... Done
E: Version '5.0.0' for 'clang' was not found

**Comment by Hax4us** [comment]
Give output of `cat $PREFIX/etc/apt/sources.list.d/hax4us.list`

**Comment by MercifulJake** [comment]
cat: can't open '/data/data/com.termux/files/usr/etc/apt/sources.list.d/hax4us.list': no such file or dictionary

**Comment by Hax4us** [comment]
You have not my repo so how can you install my packages ? 
Read instructions from README.md

**Comment by MercifulJake** [comment]
how do i accuses this? sorry im a noob.am brand new to this
