### ISSUE TITLE
Hints repo do not exist

### ISSUE THREAD

**Issue by zero-MK** [Hax4us/termux-tools#1]
$ touch $PREFIX/etc/apt/sources.list.d/hax4us.list
$ printf "\ndeb https://github.com/Hax4us/termux-tools/ termux extras" > $PREFIX/etc/apt/sources.list.d/hax4us.list
$ apt update
Hit:1 https://termux.net stable InRelease
Ign:2 https://github.com/Hax4us/termux-tools termux InRelease
Err:3 https://github.com/Hax4us/termux-tools termux Release
  404  Not Found
Reading package lists... Done
E: The repository 'https://github.com/Hax4us/termux-tools termux Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by Hax4us** [comment]
Sorry for late reply , my repo link is changed to new so add this `deb [trusted=yes] https://hax4us.github.io/termux-tools extras main` in your sources.list
