### ISSUE TITLE
Hash Sum mismatch

### ISSUE THREAD

**Issue by diggi543** [Hax4us/termux-tools#11]
Since yesterday I had an error when entering "pkg update"

E: Failed to fetch https://hax4us.github.io/termux-tools/dists/termux/extras/binary-all/Packages.xz  Hash Sum mismatch
   Hashes of expected file:
    - Filesize:1708 [weak]
    - SHA256:5bf68a59a60d308102c93c0fb0fab219f416a2326fe92280d3715057f40f0b09
   Hashes of received file:
    - SHA256:20e45b3c28617a1e929c1bd33c23270271342e113c10375862888ea5b2047bab
    - Filesize:1484 [weak]
   Last modification reported: Wed, 25 Jul 2018 10:47:05 +0000
   Release file created at: Wed, 25 Jul 2018 10:39:09 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by skykindel** [comment]
Same to me. :(

**Comment by Hax4us** [comment]
Sorry for this and now I will delete this repository for some reasons so you can add my new repo in your sources.list or separately in sources.list.d folder 
`deb [trusted=yes] https://Hax4us.github.io/termux-tools extras main`
