### ISSUE TITLE
failed installing packages

### ISSUE THREAD

**Issue by vida1j** [Hax4us/termux-tools#3]
apt install xerosploit
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have requested an impossible situation or if you are using the unstable distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
xerosploit : Depends: clang (<= 5.0.0) but 6.0.0-2 is to be installed
Depends: libllvm (<= 5.0.0) but 6.0.0-2 is to be installed E: Unable to correct problems, you have held broken packages.
Help

**Comment by vida1j** [comment]
What if I downgrade clang and libllvm to 5.0.0, and then i update all package by "apt update and apt upgrade".
it will upgrade to 6.0.0-2 again, upgrading to latest version will cause the tools?

**Comment by Hax4us** [comment]
Not tested with clang 6.0.0-2 but there was a problem in 6.0.0-1 while installing eventmachine gem but I can patch it for clang 6 also but I am busy now days , at least for 8 days ....downgrading to clang 5 will solve it temporarily I will update it soon

**Comment by Hax4us** [comment]
install new update of xerosploit it will work with latest clang and libllvm
