### ISSUE TITLE
xerosploit: depends: hping3

### ISSUE THREAD

**Issue by rmdhck** [Hax4us/termux-tools#7]
Hi... when trying to install xerosploit, in armv7 architecture, hping3 dependency occurred. But it is installable in this architecture. How to fix this problem?
....
another thing ... in a clean installation of termux does not have the sources.list.d folder in $PREFIX/etc/apt ... would have to create to add your repo ... just a note!

thx!!!

**Comment by mithunpp4u** [comment]
Same issue here unable to install in armv7

**Comment by Hax4us** [comment]
Sorry for delay ... But today I resolved your issue just update `apt update` and install `apt install xerosploit`
